version: '3.7'
services:
  mysql:
    image: mysql
    container_name: api-finance
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    restart: always
